// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

import {Test, console, Vm} from "forge-std/Test.sol";
import {CruxAttestedResolver, Proof} from "../src/CruxAttestedResolver.sol";
import {AttestSpec, Extract, Comparator} from "../src/CruxTypes.sol";
import {ICruxMarket} from "../src/ICruxMarket.sol";
import {INativeQueryVerifier} from "../src/usc/VerifierInterface.sol";
import {IChainInfo} from "../src/IChainInfo.sol";

/// @dev Records what the resolver did, so tests assert on settlement rather
///      than on events alone.
contract MockMarket is ICruxMarket {
    mapping(uint256 => bool) public settled;
    mapping(uint256 => bool) public outcome;
    mapping(uint256 => address) public resolver;

    function settle(uint256 marketId, bool yes, address who) external {
        settled[marketId] = true;
        outcome[marketId] = yes;
        resolver[marketId] = who;
    }

    function tradingCloseBlock(uint256) external pure returns (uint64) {
        return 0;
    }

    function isSettled(uint256 marketId) external view returns (bool) {
        return settled[marketId];
    }

    function register(CruxAttestedResolver r, uint256 marketId, AttestSpec memory spec) external {
        r.registerSpec(marketId, spec);
    }
}

/**
 * @notice Phase 1 — the proof lane, tested against a REAL Ethereum mainnet
 *         Chainlink price update.
 *
 * Fixture: tx 0xc11c3811…018c in block 25,829,173, a genuine ETH/USD
 * `AnswerUpdated` reporting $2,512.95. The proof was generated by the live
 * Attestcoin prover and verified TRUE by the precompile before being captured.
 *
 * The precompile itself is mocked here — it is native code with no EVM
 * bytecode, so a forked test cannot execute it (docs/phase-0.md, F2). What is
 * NOT mocked is the decoder or the transaction: every assertion below runs the
 * real EvmV1Decoder over real mainnet bytes.
 */
contract CruxAttestedResolverTest is Test {
    address constant PRECOMPILE = 0x0000000000000000000000000000000000000FD2;
    address constant CHAIN_INFO = 0x0000000000000000000000000000000000000fD3;

    address constant AGGREGATOR = 0x7d4E742018fb52E48b08BE73d041C18B21de6Fb5;
    bytes32 constant ANSWER_UPDATED =
        0x0559884fd3a460db3073b7fc896cc77986f16e378210ded43186175bf646fc5f;

    uint64 constant CHAINLINK_BLOCK = 25_829_173;
    int256 constant CHAINLINK_PRICE = 251_295_201_307; // $2,512.95 at 8dp

    CruxAttestedResolver resolver;
    MockMarket market;

    function setUp() public {
        vm.createSelectFork(vm.envString("CC3_RPC_URL"));
        market = new MockMarket();
        resolver = new CruxAttestedResolver(ICruxMarket(address(market)));
        _mockVerify(true);
        _mockTxIndex(0);
    }

    // ------------------------------------------------------------- helpers

    function _mockVerify(bool result) internal {
        vm.mockCall(
            PRECOMPILE,
            abi.encodeWithSelector(INativeQueryVerifier.verifyAndEmit.selector),
            abi.encode(result)
        );
    }

    function _mockTxIndex(uint64 idx) internal {
        vm.mockCall(
            PRECOMPILE,
            abi.encodeWithSelector(INativeQueryVerifier.calculateTxIndex.selector),
            abi.encode(idx)
        );
    }

    function _mockAttestedHeight(uint64 h) internal {
        vm.mockCall(
            CHAIN_INFO,
            abi.encodeWithSelector(IChainInfo.getLatestAttestedHeightAndHash.selector),
            abi.encode(h, bytes32(0))
        );
    }

    function _proof(string memory file) internal view returns (Proof memory p) {
        string memory json = vm.readFile(string.concat("../fixtures/", file));
        p.blockHeight = uint64(vm.parseJsonUint(json, ".headerNumber"));
        p.encodedTransaction = vm.parseJsonBytes(json, ".txBytes");
        p.merkleRoot = vm.parseJsonBytes32(json, ".merkleRoot");

        bytes32[] memory hashes = vm.parseJsonBytes32Array(json, ".siblingHashes");
        bool[] memory isLefts = vm.parseJsonBoolArray(json, ".siblingIsLeft");
        p.siblings = new INativeQueryVerifier.MerkleProofEntry[](hashes.length);
        for (uint256 i = 0; i < hashes.length; i++) {
            p.siblings[i] =
                INativeQueryVerifier.MerkleProofEntry({hash: hashes[i], isLeft: isLefts[i]});
        }
        p.lowerEndpointDigest = vm.parseJsonBytes32(json, ".lowerEndpointDigest");
        p.continuityRoots = vm.parseJsonBytes32Array(json, ".continuityRoots");
    }

    /// @dev "Will ETH be above $threshold before the window closes?"
    function _priceSpec(int256 threshold) internal pure returns (AttestSpec memory) {
        return AttestSpec({
            chainKey: 3,
            emitter: AGGREGATOR,
            topic0: ANSWER_UPDATED,
            extractMode: Extract.TOPIC,
            extractIndex: 1, // Chainlink puts the price in indexed topics[1]
            cmp: Comparator.GT,
            threshold: threshold,
            fromBlock: CHAINLINK_BLOCK - 100,
            toBlock: CHAINLINK_BLOCK + 100
        });
    }

    function _register(uint256 marketId, AttestSpec memory spec) internal {
        market.register(resolver, marketId, spec);
    }

    // --------------------------------------------------------- the thesis

    /// @notice A real mainnet Chainlink update settles a real market, with no
    ///         oracle, reporter, committee, or admin key involved.
    function test_realChainlinkUpdateSettlesMarketYes() public {
        _register(1, _priceSpec(2000e8)); // "ETH above $2,000?"
        resolver.resolveMarket(1, _proof("chainlink-answerupdated.json"));

        assertTrue(market.settled(1), "market must settle");
        assertTrue(market.outcome(1), "outcome must be YES: $2,512.95 > $2,000");
        assertEq(market.resolver(1), address(this), "bounty goes to the submitter");
    }

    /// @notice The extracted operand is the actual on-chain price, not a
    ///         placeholder — proves the topic extraction is really working.
    function test_extractedOperandIsTheRealPrice() public {
        _register(1, _priceSpec(2000e8));
        vm.recordLogs();
        resolver.resolveMarket(1, _proof("chainlink-answerupdated.json"));

        Vm.Log[] memory logs = vm.getRecordedLogs();
        int256 operand;
        for (uint256 i = 0; i < logs.length; i++) {
            if (logs[i].topics[0] == keccak256("MarketResolved(uint256,bool,address,uint64,int256)")) {
                (, operand) = abi.decode(logs[i].data, (uint64, int256));
            }
        }
        assertEq(operand, CHAINLINK_PRICE, "must extract $2,512.95 from topics[1]");
    }

    function test_predicateNotMetWhenThresholdAbovePrice() public {
        _register(1, _priceSpec(3000e8)); // "ETH above $3,000?" — it was not
        vm.expectRevert(CruxAttestedResolver.PredicateNotMet.selector);
        resolver.resolveMarket(1, _proof("chainlink-answerupdated.json"));
        assertFalse(market.settled(1));
    }

    // ------------------------------------------------------------- attacks

    /**
     * @notice The emitter check is what makes the claim mean anything.
     *
     * Event signatures are global and unowned. Anyone can deploy a contract
     * that emits `AnswerUpdated` with a price of their choosing and produce a
     * perfectly valid proof of a perfectly real transaction. Pinning the
     * emitting address is the only thing separating "Chainlink said $2,512" from
     * "somebody said $2,512".
     */
    function test_attack_matchingTopicFromWrongContractIsRejected() public {
        AttestSpec memory spec = _priceSpec(2000e8);
        spec.emitter = address(0xBEEF); // same event, impostor contract
        _register(1, spec);

        vm.expectRevert(CruxAttestedResolver.PredicateNotMet.selector);
        resolver.resolveMarket(1, _proof("chainlink-answerupdated.json"));
    }

    /**
     * @notice C3 — inclusion is not success.
     *
     * The fixture is tx 0xc3ab8c0e…1023, which REVERTED on Ethereum mainnet and
     * which the precompile nonetheless verifies as TRUE. Without the
     * receiptStatus guard an attacker resolves any market by broadcasting a
     * transaction they know will fail.
     */
    function test_attack_C3_revertedTransactionCannotResolve() public {
        AttestSpec memory spec = _priceSpec(2000e8);
        spec.fromBlock = 25_821_970;
        spec.toBlock = 25_821_990;
        _register(1, spec);

        vm.expectRevert(CruxAttestedResolver.TransactionReverted.selector);
        resolver.resolveMarket(1, _proof("mainnet-reverted.json"));
        assertFalse(market.settled(1), "a failed tx must never settle a market");
    }

    /// @notice An event outside the observation window cannot resolve it.
    function test_attack_eventOutsideWindowIsRejected() public {
        AttestSpec memory spec = _priceSpec(2000e8);
        spec.fromBlock = CHAINLINK_BLOCK + 500;
        spec.toBlock = CHAINLINK_BLOCK + 1000;
        _register(1, spec);

        vm.expectRevert(
            abi.encodeWithSelector(
                CruxAttestedResolver.BlockOutsideWindow.selector,
                CHAINLINK_BLOCK,
                CHAINLINK_BLOCK + 500,
                CHAINLINK_BLOCK + 1000
            )
        );
        resolver.resolveMarket(1, _proof("chainlink-answerupdated.json"));
    }

    function test_attack_proofRejectedByPrecompileCannotResolve() public {
        _register(1, _priceSpec(2000e8));
        _mockVerify(false);
        vm.expectRevert(CruxAttestedResolver.ProofVerificationFailed.selector);
        resolver.resolveMarket(1, _proof("chainlink-answerupdated.json"));
    }

    // -------------------------------------------------- replay granularity

    function test_replayingSameProofOnSameMarketIsBlocked() public {
        _register(1, _priceSpec(2000e8));
        resolver.resolveMarket(1, _proof("chainlink-answerupdated.json"));

        vm.expectRevert(
            abi.encodeWithSelector(CruxAttestedResolver.MarketAlreadySettled.selector, uint256(1))
        );
        resolver.resolveMarket(1, _proof("chainlink-answerupdated.json"));
    }

    /**
     * @notice The reason USCBase's replay key had to be widened.
     *
     * One Chainlink update legitimately settles many markets at once. USCBase
     * keys `processedQueries` on the transaction alone, so under its scheme the
     * first market would consume the proof and every other market referencing
     * the same event would revert "Query already processed" — permanently
     * unresolvable. Binding marketId into the key fixes that without weakening
     * replay protection.
     */
    function test_oneEventCanSettleManyMarkets() public {
        _register(1, _priceSpec(2000e8)); // "above $2,000?"
        _register(2, _priceSpec(2400e8)); // "above $2,400?"
        _register(3, _priceSpec(2500e8)); // "above $2,500?"

        resolver.resolveMarket(1, _proof("chainlink-answerupdated.json"));
        resolver.resolveMarket(2, _proof("chainlink-answerupdated.json"));
        resolver.resolveMarket(3, _proof("chainlink-answerupdated.json"));

        assertTrue(market.outcome(1) && market.outcome(2) && market.outcome(3));
    }

    // -------------------------------------------------------- NO by timeout

    function test_settleNoOnceWindowFullyAttested() public {
        _register(1, _priceSpec(2000e8));
        _mockAttestedHeight(CHAINLINK_BLOCK + 200); // past toBlock

        resolver.settleNo(1);
        assertTrue(market.settled(1));
        assertFalse(market.outcome(1), "absence established by attested time");
    }

    /**
     * @notice Settling NO before the window is fully attested would let someone
     *         close a market on an event that DID happen but has not been
     *         attested yet — the attestation lag is ~8 minutes wide.
     */
    function test_attack_settleNoBeforeWindowAttestedIsRejected() public {
        _register(1, _priceSpec(2000e8));
        _mockAttestedHeight(CHAINLINK_BLOCK); // toBlock is CHAINLINK_BLOCK + 100

        vm.expectRevert(
            abi.encodeWithSelector(
                CruxAttestedResolver.WindowNotYetAttested.selector,
                CHAINLINK_BLOCK,
                CHAINLINK_BLOCK + 100
            )
        );
        resolver.settleNo(1);
    }

    /// @notice Boundary: attested == toBlock is NOT enough. The check is
    ///         strictly greater, because toBlock itself must be behind the tip.
    function test_settleNoRejectedWhenAttestedEqualsToBlock() public {
        _register(1, _priceSpec(2000e8));
        _mockAttestedHeight(CHAINLINK_BLOCK + 100);
        vm.expectRevert();
        resolver.settleNo(1);
    }
}
